# Generated by Django 3.0.4 on 2021-02-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['createAt'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('isShow', models.BooleanField(default=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
                ('createBy', models.CharField(default='quulio', max_length=30)),
                ('updateBy', models.CharField(default='quulio', max_length=30)),
                ('isRecommend', models.BooleanField(default=False)),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Article_Type')),
            ],
            options={
                'ordering': ['createAt'],
            },
        ),
    ]
