# Generated by Django 3.0.4 on 2021-02-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Article_Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.BooleanField(default=False)),
                ('detail', models.BooleanField(default=False)),
                ('detailTopic', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('isShow', models.BooleanField(default=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Article')),
            ],
            options={
                'ordering': ['createAt'],
            },
        ),
        migrations.CreateModel(
            name='Article_Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('isShow', models.BooleanField(default=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Article')),
            ],
            options={
                'ordering': ['createAt'],
            },
        ),
    ]
