# Generated by Django 3.0.4 on 2021-02-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210219_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_image',
            name='articleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='blogs.Article'),
        ),
        migrations.AlterField(
            model_name='article_image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
